stages:
    - test_build
    - deploy

stage_test_and_deploy:
    stage: test_build
    tags:
      - test_build
    script:
      - cd /mnt/data_hdd_1/project_test/pilligrim
      - docker-compose -f docker-compose.test.yml down
      - git stash
      - git pull origin developer
      - git checkout developer
      - cd front/
      - git stash
      - git pull origin test
      - git checkout test
      - cd ..
      - docker-compose -f docker-compose.test.yml up -d --build
      - docker exec -it backend_test ./manage.py test product_eggs.tests
    only:
       - developer

    stage: deploy
    tags:
      - deploy
    script:
      - cd /home/sysadmin/project/eggs/pilligrim
      - docker-compose -f docker-compose.prod.yml down
      - git stash
      - git pull origin production
      - cd front/
      - git stash
      - git pull origin main
      - cd ..
      - docker-compose -f docker-compose.prod.yml up -d --build
    only:
       - production
