services:
  web-app: 
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/pilligrim
    env_file: .env
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database: 
    container_name: postgres
    image: postgres:14.7-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/
    # networks:
    #   - agensgraph

volumes:
  postgres:
